# Generated by Django 6.0.3 on 2026-03-15 09:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics (Phone, Laptop, etc.)'), ('books', 'Books & Stationery'), ('id_cards', 'ID / Identity Cards'), ('keys', 'Keys'), ('bags', 'Bags & Backpacks'), ('clothing', 'Clothing & Accessories'), ('jewelry', 'Jewelry & Watches'), ('wallet', 'Wallet & Money'), ('sports', 'Sports Equipment'), ('documents', 'Documents & Certificates'), ('other', 'Other')], max_length=50)),
                ('item_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('location', models.CharField(choices=[('library', 'Library'), ('cafeteria', 'Cafeteria / Food Court'), ('main_block', 'Main Block'), ('lab_block', 'Lab Block'), ('cse_dept', 'CSE Department'), ('ece_dept', 'ECE Department'), ('me_dept', 'ME Department'), ('sports_ground', 'Sports Ground'), ('hostel', 'Hostel'), ('parking', 'Parking Area'), ('auditorium', 'Auditorium'), ('canteen', 'Canteen'), ('bus_stop', 'College Bus Stop'), ('other', 'Other')], max_length=50)),
                ('location_detail', models.CharField(blank=True, max_length=200)),
                ('date_lost_found', models.DateField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('claimed', 'Claimed')], default='active', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='items.item')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('item', 'claimant')},
            },
        ),
    ]
