# Generated by Django 6.0.3 on 2026-03-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Phone/WhatsApp number (e.g. 9876543210)', max_length=15),
        ),
    ]
